### ISSUE TITLE
[Request] Do not wake for analog stick movement

### ISSUE THREAD

**Issue by SuperSamus** [foresto/joystickwake#9]
Many gamepads' analog sticks do not have a stable resting position, meaning that even if the gamepad is not touched at all, it will still send events.
For people that leave the gamepad connected via USB all the time, this means that the computer will likely never rest.
So, I'm asking if it would be possible for joystickwake to not wake the computer for analog stick movements, but only for buttons.

**Comment by foresto** [comment]
See #4.

Joystickwake's efficiency comes in part from the fact that it does not decode and process the flood of data produced by joystick devices, but simply detects it. What you are asking would cause joystickwake to consume more CPU time than I am comfortable with. (Or else require rewriting it in a compiled language like C, which I don't feel is a good use of my time right now.)

Instead, I suggest calibrating your sticks at the driver/API level:
https://wiki.archlinux.org/title/Gamepad#Setting_up_deadzones_and_calibration
